# MeDIP-seq analysis pipeline configuration

# Paths
genome_index: /beegfs/scratch/ric.broccoli/kubacki.michal/SRF_ChipSeq/mm10_bowtie2_index/mm10
adapters: "/beegfs/scratch/ric.broccoli/kubacki.michal/SRF_MeDIP/DATA/TruSeq3-PE.fa"

# Trimmomatic parameters
trimmomatic_params: "LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:36"

# MACS2 parameters
genome_size: "mm"  # for mouse genome
macs2_qvalue: 0.05

# Differential methylation analysis parameters
min_diff: 0.2
fdr_threshold: 0.05

# Functional annotation parameters
go_database: "org.Mm.eg.db"  # for mouse
kegg_database: "mmu"  # for mouse

# Output directories
fastqc_outdir: "output/fastqc"
trimmed_outdir: "output/trimmed"
aligned_outdir: "output/aligned"
dedup_outdir: "output/dedup"
peaks_outdir: "output/peaks"
diff_meth_outdir: "output/diff_meth"
func_annot_outdir: "output/func_annot"
qc_outdir: "output/qc"
bigwig_outdir: "output/bigwig"
meth_level_outdir: "output/meth_level"

# Resources
threads: 4
