# MeDIP-seq analysis pipeline configuration

# Paths
genome_index: /beegfs/scratch/ric.broccoli/kubacki.michal/SRF_CUTandTAG/mm10_bowtie2_index/mm10
adapters: "/beegfs/scratch/ric.broccoli/kubacki.michal/SRF_MeDIP/DATA/TruSeq3-PE.fa"

# Performance parameters
threads: 16  # Increased default threads
max_memory: "128G"  # Maximum memory to use

# Tool-specific parameters
trimmomatic_params: "ILLUMINACLIP:{adapters}:2:30:10 LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:36"
bowtie2_params: "--very-sensitive --no-mixed --no-discordant"
macs2_params: "--nomodel --extsize 300"

# Analysis parameters
genome_size: "mm"
macs2_qvalue: 0.05
min_diff: 0.2
fdr_threshold: 0.05

# Output directories
fastqc_outdir: "output/fastqc"
trimmed_outdir: "output/trimmed"
aligned_outdir: "output/aligned"
dedup_outdir: "output/dedup"
peaks_outdir: "output/peaks"
diff_meth_outdir: "output/diff_meth"
func_annot_outdir: "output/func_annot"
qc_outdir: "output/qc"
bigwig_outdir: "output/bigwig"
meth_level_outdir: "output/meth_level"
